spring:
  application:
    name: contacts_api
  datasource:
    url: jdbc:mysql://contacts-server.mysql.database.azure.com:3306/contacts
    username: juandlr
    password: azure@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
