spring:
  application:
    name: contacts_api
  datasource:
    url: ${MYSQLCONNSTR_CONTACTS}
    username: ${MYSQLCONNSTR_CONTACTS_USER}
    password: ${MYSQLCONNSTR_CONTACTS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
